### ISSUE TITLE
Optimisation of Buffer Initialisation within `audio_requested` default in DSP Node

### ISSUE THREAD

**Issue by mitchmindtree** [RustAudio/dsp-chain#9]
Buffer initialisation is probably the weakest point within the DSP Node at the moment. This could perhaps be fixed with a `BufferGenerator` task, who's job it could be to constantly make available cheap access to pre-initialised audio buffer handles. This would mean that receiver channels would have to be implemented within each Node, through which they could be passed ownership of a buffer. This would be collected via a `try_recv` call (that would replace the `Vec::from_elem` that currently occurs in the centre of the `audio_requested` loop).

**Comment by rryan** [comment]
It looks to me like all the memory allocation / freeing that happens throughout the graph on every audio_requested call is typically only for buffers the size of the callback. 

For the specific use case of calling a graph from an audio callback (where any memory allocation or mutex locking can cause buffer underruns and priority inversion between realtime and non-realtime threads) it seems to me that the length of the callback buffer isn't going to change for the duration of the current active PortAudio stream.

In Mixxx we pre-allocate buffers for every node in our hierarchy before engaging portaudio so all the memory allocation for the user's configured latency / buffer size doesn't happen in the callback.

Would a Graph/Node function like ```prepare(&mut self, settings: Settings)``` that allows all the nodes to pre-allocate their buffers for the provided settings make sense? Is there a use case for calling ```audio_requested``` with a different buffer size or settings each time? 

From the perspective of a GUI app where the user can pick their audio devices, you're going to shut down the PortAudio stream anyway to open a new stream with their new settings. In between closing and opening the stream you can prepare the graph for the new settings at that point.

**Comment by mitchmindtree** [comment]
@rryan You're right, there should be no change to the size of the buffer for the duration of the active PortAudio stream. Pre-allocating buffers certainly sounds like the simplest option.

Also, I knew allocations could cause underruns but I didn't know about priority inversion, I'm reading up on it now, glad you mentioned it!

Perhaps we could change the [`Graph`'s `Node` type](https://github.com/RustAudio/dsp-chain/blob/master/src/graph.rs#L16) from
```Rust
struct Node<S, D>(D, Option<Vec<S>>); // S: Sample, D: DspNode
```
to
```Rust
struct Node<S, D> {
    /// User defined DspNode type.
    node: D,
    /// The Node's sample buffer.
    buffer: Vec<S>,
    /// Indicates whether or not the buffer has already been rendered
    /// for the current audio_requested duration. This saves us from re-rendering
    /// the buffer in the case that the Node has multiple output connections.
    is_rendered: bool, 
}
```
where `buffer` is the buffer that we'll prepare beforehand and that will be passed to `node`'s `audio_requested` method.

I like the idea of a `prepare` method too, I think we could make it a Graph method quite easily:
```Rust
Graph::prepare_buffers(&mut self, settings: Settings)
```

I'm happy to do this tonight or tomorrow along with #107 as I've prepared the next couple days to work on optimisations for my synth anyway.

Thanks for dropping by btw! This has been my first serious attempt at a proper DSP graph so any input from anyone more experienced like yourself is highly appreciated :)
